### PR TITLE
update README.md

### PR DESCRIPTION
**Pull request by eduardklap**
I suggested some additions to the README file, hopefully this is helpful

### CODE REVIEW

**Comment by eduardklap** [comment]
@gorostiolam can you please review? Thanks!

**Review by gorostiolam — COMMENTED** [review]
Thanks for contributing! Please, make sure to complete the description.

**Comment by eduardklap** [comment]
I have added some more information to the README, hope this helps

**Review by gorostiolam — APPROVED** [review]
Thanks, this is perfect!

**Pull request merged**
